DROP TABLE IF EXISTS m_news;
DROP SEQUENCE IF EXISTS m_news_seq;
DROP INDEX IF EXISTS m_news_deleted_at;
DROP INDEX IF EXISTS m_news_slug;
DROP INDEX IF EXISTS m_news_version;
DROP TYPE IF EXISTS status;
